/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AnalyticsSchema extends BaseModel {
  static $columns = ['id', 'linkId', 'referrer', 'userAgent', 'ipAddress', 'country', 'city', 'device', 'browser', 'os', 'createdAt'] as const
  $columns = AnalyticsSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare linkId: string
  @column()
  declare referrer: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare ipAddress: string | null
  @column()
  declare country: string | null
  @column()
  declare city: string | null
  @column()
  declare device: string | null
  @column()
  declare browser: string | null
  @column()
  declare os: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class DomainSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'label', 'isActive', 'organizationId', 'createdAt', 'updatedAt'] as const
  $columns = DomainSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare label: string
  @column()
  declare isActive: boolean | null
  @column()
  declare organizationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LinkSchema extends BaseModel {
  static $columns = ['id', 'slugAuto', 'slugCustom', 'name', 'category', 'tags', 'targetUrl', 'userId', 'domainId', 'organizationId', 'createdAt', 'updatedAt'] as const
  $columns = LinkSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare slugAuto: string
  @column()
  declare slugCustom: string | null
  @column()
  declare name: string | null
  @column()
  declare category: string | null
  @column()
  declare tags: string | null
  @column()
  declare targetUrl: string
  @column()
  declare userId: string | null
  @column()
  declare domainId: string | null
  @column()
  declare organizationId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrganizationUserSchema extends BaseModel {
  static $columns = ['organizationId', 'userId', 'role'] as const
  $columns = OrganizationUserSchema.$columns
  @column()
  declare organizationId: string
  @column()
  declare userId: string
  @column()
  declare role: string | null
}

export class OrganizationSchema extends BaseModel {
  static $columns = ['id', 'name', 'description', 'logoUrl', 'createdAt', 'updatedAt'] as const
  $columns = OrganizationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare description: string | null
  @column()
  declare logoUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'username', 'email', 'password', 'avatarUrl', 'provider', 'providerId', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare username: string
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare avatarUrl: string | null
  @column()
  declare provider: string | null
  @column()
  declare providerId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
